imports:
    - { resource: parameters_dev.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: SUPER_SESSID
        cookie_httponly: true
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller:  app.exception_controller:showAction
    form:
        resources:
             - 'OrangeMainBundle:Extra:base_theme.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        options:
            1001: true

        default_connection: default
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            string_functions:
                GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                IFNULL: DoctrineExtensions\Query\Mysql\IfNull

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Orange\MainBundle\Entity\Utilisateur
    
    from_email:
      address: orange@orange.sn
      sender_name: SUPER
    service:
        mailer: fos_user.mailer.twig_swift
    
    registration:
        form:
            type: orange_user_registration
            
        confirmation:
            enabled: true
            
    profile:
        form:
            type: orange_user_profile
            
av_alertify:
    default:
        context: app
        engine: toastr
        layout: top-right
        translationDomain: alertify
        
monolog:
    channels: ["trace"]
    handlers:
        main_error:
            type:           rotating_file
            max_files:      366
            path:           "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.log"
            level:          info
            action_level:   info
            channels:       ["trace"]
            formatter:      orange.quickmaking_formatter

#fr3d_ldap
fr3d_ldap:
    driver:
        host:     10.100.55.80
        port:     389
        accountDomainName: orange-sonatel.com
    user:
        baseDn: dc=orange-sonatel, dc=com
        filter: (objectclass=user)
        attributes:         
           - { ldap_attr: samaccountname,  user_method: setUsername }
           
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_menu:
    twig: # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false   #  if true, enables the helper for PHP templates
    default_renderer: twig  # the renderer to use, list is also available by default

# FOS Rest
fos_rest:
    zone:
        - { path: ^/api/* }
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true } # Available for version >= 1.5
    exception:
        enabled: true
        exception_controller: app.exception_controller:showApiAction
    view:
        view_response_listener: true
        formats:
            json: true
            xml:  false
        mime_types:
            json: ['application/json']
    routing_loader:
        default_format: json
        include_format: false
    serializer:
        serialize_null: true
    body_converter:
        enabled: false
    access_denied_listener:
        json: true
    body_converter:
        enabled: true

nelmio_cors:
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'GET']
            max_age: 3600
            
nelmio_api_doc:
    name:                   Documentation sur les Webervices
    cache:
        enabled:            false
        file:               '%kernel.cache_dir%/api-doc.cache'
    